/**
 * Core Verifiers - The proof engine
 *
 * Per PRD: Verifiers are triggered deterministically but evaluated agentically.
 * They produce PASS/FAIL + evidence, enabling honest capability assessment.
 *
 * No verifier = not proven. Self-report does not count.
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import { existsSync, readFileSync, readdirSync } from 'fs';
import path from 'path';

const execAsync = promisify(exec);

/**
 * Known framework/agent artifacts that should be excluded from git status checks.
 * These files are generated by the agent framework, not by the worker.
 */
const FRAMEWORK_ARTIFACT_PATTERNS = [
  /^STEP-\d+-COMPLETE\.md$/,
  /^RESEARCH\.md$/,
  /^PLAN\.md$/,
  /^NOTES\.md$/,
  /\.handoff\.md$/,
];

/**
 * Path prefixes for directories that contain agent/tool artifacts (not worker code).
 * Files under these paths are excluded from git_status_clean checks.
 */
const ARTIFACT_DIR_PREFIXES = [
  '.playwright-cli/',
  '.playwright-mcp/',
];

/**
 * Detect the actual git project root within an output_path.
 * Workers sometimes create apps in a subdirectory (e.g., output_path/music-player/).
 * Returns the subdirectory path if a .git dir is found there, or null.
 */
function findSubdirectoryGitRoot(projectPath: string): string | null {
  try {
    const entries = readdirSync(projectPath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith('.')) continue;
      const subDir = path.join(projectPath, entry.name);
      if (existsSync(path.join(subDir, '.git'))) {
        return subDir;
      }
    }
  } catch {
    // ignore
  }
  return null;
}

/**
 * Filter out known framework artifacts from git status output lines.
 */
function filterFrameworkArtifacts(changedFiles: string[]): string[] {
  return changedFiles.filter(line => {
    // Extract the full relative path from git status line (format: "XY path/to/file")
    const filePath = line.replace(/^.{2}\s+/, '').replace(/^"(.*)"$/, '$1');
    const fileName = filePath.split('/').pop() || '';

    // Exclude files matching known framework artifact patterns
    if (FRAMEWORK_ARTIFACT_PATTERNS.some(pattern => pattern.test(fileName))) return false;

    // Exclude files under known artifact directories
    if (ARTIFACT_DIR_PREFIXES.some(prefix => filePath.startsWith(prefix))) return false;

    return true;
  });
}

export interface VerifierResult {
  verifier_id: string;
  result: 'PASS' | 'FAIL';
  message: string;
  evidence: Record<string, unknown>;
  duration_ms: number;
}

export interface VerifierConfig {
  project_path: string;
  timeout_ms?: number;
}

/**
 * Step context for step-aware validation
 */
export interface StepContext {
  step_number: number;
  step_title: string;
  total_steps: number;
}

/**
 * Determine step type from step title and number
 * Research/planning steps get lighter validation
 */
function getStepType(step?: StepContext): 'research' | 'setup' | 'implementation' | 'testing' | 'unknown' {
  if (!step) return 'unknown';

  const title = step.step_title.toLowerCase();

  // Step 1 is typically research/planning
  if (step.step_number === 0 ||
      title.includes('research') ||
      title.includes('plan') ||
      title.includes('analyze') ||
      title.includes('investigate')) {
    return 'research';
  }

  // Setup/initialization step
  if (title.includes('initialize') ||
      title.includes('setup') ||
      title.includes('scaffold') ||
      title.includes('project structure')) {
    return 'setup';
  }

  // Testing step
  if (title.includes('test') ||
      title.includes('quality') ||
      title.includes('qa')) {
    return 'testing';
  }

  // Default to implementation for other steps
  return 'implementation';
}

/**
 * Verifier 1: git_status_clean
 * Checks that the git working tree is clean (no uncommitted changes)
 */
export async function verifyGitStatusClean(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  let { project_path } = config;

  try {
    // Check if project_path itself is a git repo
    const hasGitDir = existsSync(path.join(project_path, '.git'));

    if (!hasGitDir) {
      // Workers sometimes create apps in a subdirectory of output_path.
      // Look for a subdirectory that contains .git/
      const subRoot = findSubdirectoryGitRoot(project_path);
      if (subRoot) {
        project_path = subRoot;
      } else {
        // No git repo found at all — this is acceptable, not a failure
        return {
          verifier_id: 'git_status_clean',
          result: 'PASS',
          message: 'No git repository found (project may not use git)',
          evidence: { clean: true, no_git: true },
          duration_ms: Date.now() - start,
        };
      }
    }

    const { stdout } = await execAsync('git status --porcelain', {
      cwd: project_path,
      timeout: config.timeout_ms || 10000,
    });

    const rawChangedFiles = stdout.trim().split('\n').filter(Boolean);
    // Filter out known agent framework artifacts
    const changedFiles = filterFrameworkArtifacts(rawChangedFiles);
    const isClean = changedFiles.length === 0;

    return {
      verifier_id: 'git_status_clean',
      result: isClean ? 'PASS' : 'FAIL',
      message: isClean ? 'Working tree is clean' : `${changedFiles.length} uncommitted changes`,
      evidence: {
        clean: isClean,
        changed_files: changedFiles.slice(0, 10),
        ...(project_path !== config.project_path ? { actual_git_root: project_path } : {}),
        ...(rawChangedFiles.length !== changedFiles.length ? { filtered_artifacts: rawChangedFiles.length - changedFiles.length } : {}),
      },
      duration_ms: Date.now() - start,
    };
  } catch (error) {
    return {
      verifier_id: 'git_status_clean',
      result: 'FAIL',
      message: `Git check failed: ${error instanceof Error ? error.message : String(error)}`,
      evidence: { error: true },
      duration_ms: Date.now() - start,
    };
  }
}

/**
 * Verifier 2: commit_exists
 * Checks that at least one commit exists in the repo
 */
export async function verifyCommitExists(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  try {
    const { stdout } = await execAsync('git log --oneline -5', {
      cwd: project_path,
      timeout: config.timeout_ms || 10000,
    });

    const commits = stdout.trim().split('\n').filter(Boolean);
    const hasCommits = commits.length > 0;

    return {
      verifier_id: 'commit_exists',
      result: hasCommits ? 'PASS' : 'FAIL',
      message: hasCommits ? `Found ${commits.length} recent commits` : 'No commits found',
      evidence: {
        commit_count: commits.length,
        recent_commits: commits.slice(0, 5),
      },
      duration_ms: Date.now() - start,
    };
  } catch (error) {
    return {
      verifier_id: 'commit_exists',
      result: 'FAIL',
      message: `Git log failed: ${error instanceof Error ? error.message : String(error)}`,
      evidence: { error: true },
      duration_ms: Date.now() - start,
    };
  }
}

/**
 * Verifier 3: files_exist
 * Checks that required files exist
 */
export async function verifyFilesExist(
  config: VerifierConfig,
  requiredFiles: string[]
): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  const results: Record<string, boolean> = {};
  const missing: string[] = [];

  for (const file of requiredFiles) {
    const fullPath = path.join(project_path, file);
    const exists = existsSync(fullPath);
    results[file] = exists;
    if (!exists) {
      missing.push(file);
    }
  }

  const allExist = missing.length === 0;

  return {
    verifier_id: 'files_exist',
    result: allExist ? 'PASS' : 'FAIL',
    message: allExist ? `All ${requiredFiles.length} required files exist` : `Missing: ${missing.join(', ')}`,
    evidence: {
      files_checked: results,
      missing,
    },
    duration_ms: Date.now() - start,
  };
}

/**
 * Verifier 4: node_install
 * Checks that npm install/ci succeeds
 */
export async function verifyNodeInstall(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  // Check if package.json exists
  const packageJsonPath = path.join(project_path, 'package.json');
  if (!existsSync(packageJsonPath)) {
    return {
      verifier_id: 'node_install',
      result: 'FAIL',
      message: 'No package.json found',
      evidence: { package_json_exists: false },
      duration_ms: Date.now() - start,
    };
  }

  try {
    // Use npm ci for reproducible installs, fall back to npm install
    const { stdout, stderr } = await execAsync('npm ci || npm install', {
      cwd: project_path,
      timeout: config.timeout_ms || 120000, // 2 min timeout
    });

    return {
      verifier_id: 'node_install',
      result: 'PASS',
      message: 'npm install succeeded',
      evidence: {
        stdout: stdout.slice(-500),
        stderr: stderr.slice(-500),
      },
      duration_ms: Date.now() - start,
    };
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    return {
      verifier_id: 'node_install',
      result: 'FAIL',
      message: `npm install failed: ${errorMsg.slice(0, 200)}`,
      evidence: {
        error: errorMsg.slice(0, 1000),
      },
      duration_ms: Date.now() - start,
    };
  }
}

/**
 * Verifier 5: node_build
 * Checks that npm run build succeeds
 */
export async function verifyNodeBuild(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  // Check if build script exists
  const packageJsonPath = path.join(project_path, 'package.json');
  if (!existsSync(packageJsonPath)) {
    return {
      verifier_id: 'node_build',
      result: 'FAIL',
      message: 'No package.json found',
      evidence: { package_json_exists: false },
      duration_ms: Date.now() - start,
    };
  }

  try {
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
    if (!packageJson.scripts?.build) {
      return {
        verifier_id: 'node_build',
        result: 'FAIL',
        message: 'No build script in package.json',
        evidence: { has_build_script: false },
        duration_ms: Date.now() - start,
      };
    }
  } catch (e) {
    return {
      verifier_id: 'node_build',
      result: 'FAIL',
      message: 'Failed to parse package.json',
      evidence: { parse_error: true },
      duration_ms: Date.now() - start,
    };
  }

  try {
    const { stdout, stderr } = await execAsync('npm run build', {
      cwd: project_path,
      timeout: config.timeout_ms || 300000, // 5 min timeout
    });

    return {
      verifier_id: 'node_build',
      result: 'PASS',
      message: 'Build succeeded',
      evidence: {
        stdout: stdout.slice(-500),
        stderr: stderr.slice(-500),
      },
      duration_ms: Date.now() - start,
    };
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    return {
      verifier_id: 'node_build',
      result: 'FAIL',
      message: `Build failed: ${errorMsg.slice(0, 200)}`,
      evidence: {
        error: errorMsg.slice(0, 1000),
      },
      duration_ms: Date.now() - start,
    };
  }
}

/**
 * Verifier 6: node_test
 * Checks that npm test succeeds (if tests exist)
 */
export async function verifyNodeTest(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  const packageJsonPath = path.join(project_path, 'package.json');
  if (!existsSync(packageJsonPath)) {
    return {
      verifier_id: 'node_test',
      result: 'FAIL',
      message: 'No package.json found',
      evidence: { package_json_exists: false },
      duration_ms: Date.now() - start,
    };
  }

  try {
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
    if (!packageJson.scripts?.test || packageJson.scripts.test === 'echo "Error: no test specified" && exit 1') {
      // No tests configured - this is a PASS with note
      return {
        verifier_id: 'node_test',
        result: 'PASS',
        message: 'No test script configured (acceptable for MVP)',
        evidence: { has_test_script: false, note: 'No tests to run' },
        duration_ms: Date.now() - start,
      };
    }
  } catch (e) {
    return {
      verifier_id: 'node_test',
      result: 'FAIL',
      message: 'Failed to parse package.json',
      evidence: { parse_error: true },
      duration_ms: Date.now() - start,
    };
  }

  try {
    const { stdout, stderr } = await execAsync('npm test', {
      cwd: project_path,
      timeout: config.timeout_ms || 120000, // 2 min timeout
    });

    return {
      verifier_id: 'node_test',
      result: 'PASS',
      message: 'Tests passed',
      evidence: {
        stdout: stdout.slice(-500),
        stderr: stderr.slice(-500),
      },
      duration_ms: Date.now() - start,
    };
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    return {
      verifier_id: 'node_test',
      result: 'FAIL',
      message: `Tests failed: ${errorMsg.slice(0, 200)}`,
      evidence: {
        error: errorMsg.slice(0, 1000),
      },
      duration_ms: Date.now() - start,
    };
  }
}

/**
 * Verifier 7: lint_pass
 * Checks that linting passes (if configured)
 */
export async function verifyLintPass(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  const packageJsonPath = path.join(project_path, 'package.json');
  if (!existsSync(packageJsonPath)) {
    return {
      verifier_id: 'lint_pass',
      result: 'PASS',
      message: 'No package.json - linting not applicable',
      evidence: { package_json_exists: false },
      duration_ms: Date.now() - start,
    };
  }

  try {
    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
    if (!packageJson.scripts?.lint) {
      return {
        verifier_id: 'lint_pass',
        result: 'PASS',
        message: 'No lint script configured',
        evidence: { has_lint_script: false },
        duration_ms: Date.now() - start,
      };
    }
  } catch (e) {
    return {
      verifier_id: 'lint_pass',
      result: 'FAIL',
      message: 'Failed to parse package.json',
      evidence: { parse_error: true },
      duration_ms: Date.now() - start,
    };
  }

  try {
    const { stdout, stderr } = await execAsync('npm run lint', {
      cwd: project_path,
      timeout: config.timeout_ms || 60000, // 1 min timeout
    });

    return {
      verifier_id: 'lint_pass',
      result: 'PASS',
      message: 'Linting passed',
      evidence: {
        stdout: stdout.slice(-500),
        stderr: stderr.slice(-500),
      },
      duration_ms: Date.now() - start,
    };
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    return {
      verifier_id: 'lint_pass',
      result: 'FAIL',
      message: `Linting failed: ${errorMsg.slice(0, 200)}`,
      evidence: {
        error: errorMsg.slice(0, 1000),
      },
      duration_ms: Date.now() - start,
    };
  }
}

/**
 * Verifier 8: docs_checklist
 * Checks that basic documentation exists
 */
export async function verifyDocsChecklist(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;

  const checks: Record<string, boolean> = {};
  const issues: string[] = [];

  // Check README exists
  const readmePath = path.join(project_path, 'README.md');
  checks['readme_exists'] = existsSync(readmePath);
  if (!checks['readme_exists']) {
    issues.push('Missing README.md');
  }

  // Check README has content
  if (checks['readme_exists']) {
    const content = readFileSync(readmePath, 'utf-8');
    checks['readme_has_content'] = content.length > 50;
    if (!checks['readme_has_content']) {
      issues.push('README.md is too short (< 50 chars)');
    }

    // Check for run instructions
    const hasRunInstructions =
      content.toLowerCase().includes('npm run') ||
      content.toLowerCase().includes('how to run') ||
      content.toLowerCase().includes('getting started') ||
      content.toLowerCase().includes('installation');
    checks['has_run_instructions'] = hasRunInstructions;
    if (!hasRunInstructions) {
      issues.push('README missing run instructions');
    }
  }

  const allPassing = issues.length === 0;

  return {
    verifier_id: 'docs_checklist',
    result: allPassing ? 'PASS' : 'FAIL',
    message: allPassing ? 'Documentation checklist passed' : `Issues: ${issues.join(', ')}`,
    evidence: {
      checks,
      issues,
    },
    duration_ms: Date.now() - start,
  };
}

/**
 * Verifier 9: skill_format
 * Validates Claude Code skill directories under {project_path}/.claude/skills/
 * Checks SKILL.md existence, frontmatter validity, and script executability.
 */
export async function verifySkillFormat(config: VerifierConfig): Promise<VerifierResult> {
  const start = Date.now();
  const { project_path } = config;
  const skillsDir = path.join(project_path, '.claude', 'skills');

  if (!existsSync(skillsDir)) {
    return {
      verifier_id: 'skill_format',
      result: 'FAIL',
      message: 'No .claude/skills/ directory found',
      evidence: { skills_dir_exists: false },
      duration_ms: Date.now() - start,
    };
  }

  const issues: string[] = [];
  const checked: string[] = [];

  // Find skill directories (immediate subdirectories of .claude/skills/)
  let skillDirs: string[];
  try {
    const entries = readdirSync(skillsDir, { withFileTypes: true });
    skillDirs = entries
      .filter(e => e.isDirectory() && !e.name.startsWith('.') && !e.name.startsWith('_'))
      .map(e => e.name);
  } catch {
    return {
      verifier_id: 'skill_format',
      result: 'FAIL',
      message: 'Failed to read .claude/skills/ directory',
      evidence: { read_error: true },
      duration_ms: Date.now() - start,
    };
  }

  if (skillDirs.length === 0) {
    return {
      verifier_id: 'skill_format',
      result: 'FAIL',
      message: 'No skill directories found in .claude/skills/',
      evidence: { skill_count: 0 },
      duration_ms: Date.now() - start,
    };
  }

  const ALLOWED_FRONTMATTER_KEYS = new Set(['name', 'description', 'license', 'allowed-tools', 'metadata']);

  for (const skillName of skillDirs) {
    const skillDir = path.join(skillsDir, skillName);
    checked.push(skillName);

    // Check SKILL.md exists
    const skillMdPath = path.join(skillDir, 'SKILL.md');
    if (!existsSync(skillMdPath)) {
      issues.push(`${skillName}: Missing SKILL.md`);
      continue;
    }

    // Parse frontmatter
    let content: string;
    try {
      content = readFileSync(skillMdPath, 'utf-8');
    } catch {
      issues.push(`${skillName}: Failed to read SKILL.md`);
      continue;
    }

    const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
    if (!fmMatch) {
      issues.push(`${skillName}: No YAML frontmatter found in SKILL.md`);
      continue;
    }

    // Simple YAML key-value parsing (avoids needing js-yaml import here)
    const fmLines = fmMatch[1].split('\n');
    const frontmatter: Record<string, string> = {};
    let currentKey = '';
    let currentValue = '';
    let inMultiline = false;

    for (const line of fmLines) {
      const keyMatch = line.match(/^(\w[\w-]*):\s*(.*)/);
      if (keyMatch && !inMultiline) {
        if (currentKey) frontmatter[currentKey] = currentValue.trim();
        currentKey = keyMatch[1];
        const val = keyMatch[2].trim();
        if (val === '|' || val === '>') {
          inMultiline = true;
          currentValue = '';
        } else {
          currentValue = val;
          inMultiline = false;
        }
      } else if (inMultiline && line.match(/^\s/)) {
        currentValue += (currentValue ? '\n' : '') + line.trimStart();
      } else if (inMultiline && !line.match(/^\s/) && line.trim() !== '') {
        // End of multiline block
        frontmatter[currentKey] = currentValue.trim();
        const newKeyMatch = line.match(/^(\w[\w-]*):\s*(.*)/);
        if (newKeyMatch) {
          currentKey = newKeyMatch[1];
          const val = newKeyMatch[2].trim();
          if (val === '|' || val === '>') {
            inMultiline = true;
            currentValue = '';
          } else {
            currentValue = val;
            inMultiline = false;
          }
        }
      }
    }
    if (currentKey) frontmatter[currentKey] = currentValue.trim();

    // Validate name
    if (!frontmatter['name']) {
      issues.push(`${skillName}: Missing 'name' in frontmatter`);
    } else {
      const name = frontmatter['name'];
      if (name.length > 64) {
        issues.push(`${skillName}: 'name' exceeds 64 characters (${name.length})`);
      }
      if (!/^[a-z][a-z0-9-]*[a-z0-9]$/.test(name) && name.length > 1) {
        // Allow single char names too
        if (!/^[a-z]$/.test(name)) {
          issues.push(`${skillName}: 'name' must be lowercase with hyphens, no leading/trailing/consecutive hyphens`);
        }
      }
      if (/--/.test(frontmatter['name'])) {
        issues.push(`${skillName}: 'name' contains consecutive hyphens`);
      }
    }

    // Validate description
    if (!frontmatter['description']) {
      issues.push(`${skillName}: Missing 'description' in frontmatter`);
    } else {
      if (frontmatter['description'].length > 1024) {
        issues.push(`${skillName}: 'description' exceeds 1024 characters`);
      }
      if (/<[^>]+>/.test(frontmatter['description'])) {
        issues.push(`${skillName}: 'description' contains angle brackets (potential HTML/injection)`);
      }
    }

    // Check for disallowed frontmatter keys
    for (const key of Object.keys(frontmatter)) {
      if (!ALLOWED_FRONTMATTER_KEYS.has(key)) {
        issues.push(`${skillName}: Unknown frontmatter key '${key}'`);
      }
    }

    // Check scripts are executable (if scripts/ dir exists)
    const scriptsDir = path.join(skillDir, 'scripts');
    if (existsSync(scriptsDir)) {
      try {
        const scriptEntries = readdirSync(scriptsDir, { withFileTypes: true });
        for (const entry of scriptEntries) {
          if (!entry.isFile() || entry.name.startsWith('.')) continue;
          try {
            const { stdout } = await execAsync(`test -x "${path.join(scriptsDir, entry.name)}" && echo "OK" || echo "NO"`, {
              timeout: 5000,
            });
            if (stdout.trim() !== 'OK') {
              issues.push(`${skillName}: scripts/${entry.name} is not executable`);
            }
          } catch {
            issues.push(`${skillName}: Failed to check scripts/${entry.name} executability`);
          }
        }
      } catch {
        issues.push(`${skillName}: Failed to read scripts/ directory`);
      }
    }
  }

  const allPassing = issues.length === 0;

  return {
    verifier_id: 'skill_format',
    result: allPassing ? 'PASS' : 'FAIL',
    message: allPassing
      ? `All ${checked.length} skill(s) pass format validation`
      : `${issues.length} issue(s) found across ${checked.length} skill(s)`,
    evidence: {
      skills_checked: checked,
      issues,
    },
    duration_ms: Date.now() - start,
  };
}

/**
 * Task type for routing validation logic
 */
export type GoalType = 'standard' | 'skill-build' | 'self-enhance';

/**
 * Run applicable verifiers for a project based on step context and task type
 *
 * Task-type routing:
 * - skill-build: git clean + skill format only
 * - self-enhance: git clean + node build only
 * - standard: step-aware validation (research/setup/implementation)
 *
 * Step-aware validation (standard tasks):
 * - Research steps: Only check git clean and that some output exists
 * - Setup steps: Check git clean, files created, npm install works
 * - Implementation/Testing: Full validation suite
 * - Unknown (no step info): Full validation for backwards compatibility
 */
export async function runAllVerifiers(
  config: VerifierConfig,
  step?: StepContext,
  taskType?: GoalType
): Promise<VerifierResult[]> {
  const results: VerifierResult[] = [];

  // Task-type routing: skill-build and self-enhance have specialised verifier sets
  if (taskType === 'skill-build') {
    results.push(await verifyGitStatusClean(config));
    results.push(await verifySkillFormat(config));
    return results;
  }

  if (taskType === 'self-enhance') {
    results.push(await verifyGitStatusClean(config));
    results.push(await verifyNodeBuild(config));
    return results;
  }

  const stepType = getStepType(step);

  // Git status clean is ALWAYS required - work must be committed
  results.push(await verifyGitStatusClean(config));

  // Research/planning steps: minimal validation
  // Just need git clean and some output (research docs, notes, etc.)
  if (stepType === 'research') {
    // Check that at least SOME files exist (research output, markdown docs, etc.)
    // Accept common research outputs, not just code files
    const researchFiles = ['RESEARCH.md', 'research.md', 'PLAN.md', 'plan.md', 'README.md', 'NOTES.md', 'notes.md'];
    const anyResearchFilePath = path.join(config.project_path, 'RESEARCH.md');
    let hasAnyOutput = false;

    // Check if any research-type file exists
    for (const file of researchFiles) {
      if (existsSync(path.join(config.project_path, file))) {
        hasAnyOutput = true;
        break;
      }
    }

    // Also accept package.json or any .md file as valid research output
    if (!hasAnyOutput && existsSync(path.join(config.project_path, 'package.json'))) {
      hasAnyOutput = true;
    }

    results.push({
      verifier_id: 'research_output_exists',
      result: hasAnyOutput ? 'PASS' : 'FAIL',
      message: hasAnyOutput ? 'Research output files exist' : 'No research output found (expected RESEARCH.md, PLAN.md, or similar)',
      evidence: { step_type: stepType, checked_files: researchFiles },
      duration_ms: 0,
    });

    return results;
  }

  // Setup steps: check project structure created
  if (stepType === 'setup') {
    // For setup, we want basic structure but not necessarily full build
    results.push(await verifyFilesExist(config, ['package.json']));
    results.push(await verifyNodeInstall(config));
    // Skip build/test for setup - those come in later steps
    return results;
  }

  // Implementation and testing steps: full validation
  // Also default for unknown step type (backwards compatibility)
  results.push(await verifyFilesExist(config, ['package.json', 'README.md']));
  results.push(await verifyNodeInstall(config));
  results.push(await verifyNodeBuild(config));
  results.push(await verifyNodeTest(config));
  results.push(await verifyLintPass(config));
  results.push(await verifyDocsChecklist(config));

  return results;
}

/**
 * Summarize verifier results
 */
export function summarizeResults(results: VerifierResult[]): {
  overall: 'PASS' | 'FAIL' | 'PARTIAL';
  pass_count: number;
  fail_count: number;
  summary: string;
} {
  const pass_count = results.filter(r => r.result === 'PASS').length;
  const fail_count = results.filter(r => r.result === 'FAIL').length;

  let overall: 'PASS' | 'FAIL' | 'PARTIAL';
  if (fail_count === 0) {
    overall = 'PASS';
  } else if (pass_count === 0) {
    overall = 'FAIL';
  } else {
    overall = 'PARTIAL';
  }

  const summary = `${pass_count}/${results.length} verifiers passed`;

  return { overall, pass_count, fail_count, summary };
}
